# Generated by Django 3.2 on 2021-05-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('datumRodj', models.DateField()),
                ('email', models.CharField(max_length=200)),
                ('ugovorVazi', models.DateField()),
                ('napomena', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
