# Generated by Django 3.2 on 2021-05-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('godina', models.IntegerField()),
                ('datumUclanjenja', models.DateField()),
                ('email', models.CharField(max_length=200)),
                ('datumVazi', models.DateField()),
                ('napomena', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('datumUposlenja', models.DateField()),
                ('email', models.CharField(max_length=200)),
                ('datumIstekaUgovora', models.DateField()),
                ('napomena', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
