# Generated by Django 3.2 on 2021-05-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210511_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='napomena',
        ),
        migrations.RemoveField(
            model_name='players',
            name='pozicijaa',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='napomena',
        ),
        migrations.AddField(
            model_name='players',
            name='pozicija',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='napomena',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='staff',
            name='pozicijaa',
        ),
        migrations.AddField(
            model_name='staff',
            name='pozicijaa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Pozicija',
        ),
    ]
