# Generated by Django 3.2 on 2021-06-27 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210624_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='datumUclanjenja',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='datumUposlenja',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
