# Generated by Django 3.2 on 2021-06-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210627_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponzors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Tip_Sponzorstva', models.CharField(max_length=200)),
                ('Cijena_sponzorstva', models.IntegerField()),
            ],
        ),
    ]
