# Generated by Django 3.2 on 2021-07-09 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sponzors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prihod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naziv_lica', models.CharField(max_length=100)),
                ('Tip_Uplate', models.CharField(max_length=200)),
                ('Datum_uplate', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('Cijena', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rashod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naziv_lica', models.CharField(max_length=100)),
                ('Tip_Uplate', models.CharField(max_length=200)),
                ('Datum_uplate', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('Cijena', models.IntegerField()),
            ],
        ),
    ]
